package com.wym.mapper;

import com.wym.model.Company;
import com.wym.model.CompanyExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface CompanyMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @SelectProvider(type=CompanySqlProvider.class, method="countByExample")
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @DeleteProvider(type=CompanySqlProvider.class, method="deleteByExample")
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @Delete({
        "delete from company",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @Insert({
        "insert into company (cid, name, ",
        "address, pro, city, ",
        "price)",
        "values (#{cid,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{pro,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=INTEGER})"
    })
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @InsertProvider(type=CompanySqlProvider.class, method="insertSelective")
    int insertSelective(Company record);
    @Select({
            "select",
            "cid, name, address, pro, city, price",
            "from company",
            "where cid = #{cid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
            @Result(column="pro", property="pro", jdbcType=JdbcType.VARCHAR),
            @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
            @Result(column = "cid",property="elist",javaType = List.class
                    ,many=@Many(select="com.wym.mapper.EmpMapper.selectEmpsByCid"))
    })
    Company selectByPrimaryKey(Integer cid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @SelectProvider(type=CompanySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="pro", property="pro", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER)
    })
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @UpdateProvider(type=CompanySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @UpdateProvider(type=CompanySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @UpdateProvider(type=CompanySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    @Update({
        "update company",
        "set name = #{name,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "pro = #{pro,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=INTEGER}",
        "where cid = #{cid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Company record);
}