package com.wym.model;

import java.io.Serializable;

public class Company implements Serializable {
     private Object elist;//必须用Object

    public Object getElist() {
        return elist;
    }

    public void setElist(Object elist) {
        this.elist = elist;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cid
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.pro
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    private String pro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.city
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.price
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cid
     *
     * @return the value of company.cid
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cid
     *
     * @param cid the value for company.cid
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.pro
     *
     * @return the value of company.pro
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public String getPro() {
        return pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.pro
     *
     * @param pro the value for company.pro
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public void setPro(String pro) {
        this.pro = pro == null ? null : pro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.city
     *
     * @return the value of company.city
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.city
     *
     * @param city the value for company.city
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.price
     *
     * @return the value of company.price
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.price
     *
     * @param price the value for company.price
     *
     * @mbg.generated Wed Jan 17 16:58:27 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}